CREATE TABLE usuario (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	username VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR(120) NOT NULL,
	enabled BOOLEAN DEFAULT true NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
