CREATE TABLE administrador (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	CONSTRAINT usuario_administrador FOREIGN KEY (id) REFERENCES usuario (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
