CREATE TABLE candidato (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	cpf VARCHAR(11) NOT NULL UNIQUE,
	telefone VARCHAR(11) NOT NULL,
	curriculo BIGINT(20) NOT NULL,
	CONSTRAINT usuario_candidato FOREIGN KEY (id) REFERENCES usuario (id) ON DELETE CASCADE,
	FOREIGN KEY (curriculo) REFERENCES arquivo(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
